#!/bin/bash
#
# Glassmorphic File Manager - Installation Script
#
# This script installs the file manager on a Debian/Ubuntu server.
# Run as root or with sudo.
#
# Usage: sudo ./install.sh
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
INSTALL_DIR="/opt/glassfile"
SERVICE_USER="filemanager"
SERVICE_GROUP="filemanager"
LOG_DIR="/var/log/glassfile"

# Functions
print_header() {
    echo -e "\n${CYAN}========================================${NC}"
    echo -e "${CYAN}  Glassmorphic File Manager Installer${NC}"
    echo -e "${CYAN}========================================${NC}\n"
}

print_step() {
    echo -e "${GREEN}[*]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

check_python() {
    print_step "Checking Python version..."

    if ! command -v python3 &> /dev/null; then
        print_error "Python 3 is not installed"
        echo "Install with: apt install python3 python3-pip python3-venv"
        exit 1
    fi

    PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    print_success "Python $PYTHON_VERSION found"

    # Check minimum version (3.8)
    if python3 -c 'import sys; exit(0 if sys.version_info >= (3, 8) else 1)'; then
        print_success "Python version is compatible"
    else
        print_error "Python 3.8 or higher is required"
        exit 1
    fi
}

create_user() {
    print_step "Creating service user..."

    if id "$SERVICE_USER" &>/dev/null; then
        print_warning "User '$SERVICE_USER' already exists"
    else
        useradd --system --no-create-home --shell /bin/false "$SERVICE_USER"
        print_success "Created user '$SERVICE_USER'"
    fi
}

create_directories() {
    print_step "Creating directories..."

    # Installation directory
    mkdir -p "$INSTALL_DIR"
    mkdir -p "$INSTALL_DIR/static/files"
    mkdir -p "$INSTALL_DIR/templates"

    # Log directory
    mkdir -p "$LOG_DIR"

    print_success "Directories created"
}

copy_files() {
    print_step "Copying application files..."

    # Get the directory where this script is located
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Copy application files
    cp "$SCRIPT_DIR/fileserver.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/filemanager" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/requirements.txt" "$INSTALL_DIR/"
    cp -r "$SCRIPT_DIR/templates/"* "$INSTALL_DIR/templates/"

    # Make CLI executable
    chmod +x "$INSTALL_DIR/filemanager"

    print_success "Files copied"
}

setup_venv() {
    print_step "Setting up Python virtual environment..."

    python3 -m venv "$INSTALL_DIR/venv"
    source "$INSTALL_DIR/venv/bin/activate"

    pip install --upgrade pip -q
    pip install -r "$INSTALL_DIR/requirements.txt" -q

    deactivate

    print_success "Virtual environment created and dependencies installed"
}

generate_credentials() {
    print_step "Generating secure credentials..."

    # Generate password hash for 'admin' (user should change this)
    ADMIN_PASSWORD=$(openssl rand -base64 12)
    PASSWORD_HASH=$("$INSTALL_DIR/venv/bin/python3" -c "from werkzeug.security import generate_password_hash; print(generate_password_hash('$ADMIN_PASSWORD'))")

    # Generate API key
    API_KEY=$(openssl rand -base64 32 | tr -d '/+=' | head -c 43)

    print_success "Credentials generated"
    echo ""
    echo -e "  ${YELLOW}IMPORTANT: Save these credentials!${NC}"
    echo -e "  ${CYAN}Admin Password:${NC} $ADMIN_PASSWORD"
    echo -e "  ${CYAN}API Key:${NC}        $API_KEY"
    echo ""
}

create_config() {
    print_step "Creating configuration file..."

    cat > "$INSTALL_DIR/config.yaml" << EOF
# Glassmorphic File Manager Configuration
# Generated by install.sh on $(date)

server:
  host: '0.0.0.0'
  port: 8080
  debug: false

storage:
  directory: './static/files'
  max_file_size: 104857600  # 100MB
  allowed_extensions: null   # null = all allowed

security:
  admin_password_hash: '$PASSWORD_HASH'
  api_keys:
    - '$API_KEY'
  session_lifetime: 3600
  ip_whitelist: []

display:
  files_per_page: 50
  date_format: 'relative'
EOF

    # Secure the config file
    chmod 600 "$INSTALL_DIR/config.yaml"

    print_success "Configuration file created"
}

set_permissions() {
    print_step "Setting file permissions..."

    # Set ownership
    chown -R "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_DIR"
    chown -R "$SERVICE_USER:$SERVICE_GROUP" "$LOG_DIR"

    # Set directory permissions
    chmod 755 "$INSTALL_DIR"
    chmod 755 "$INSTALL_DIR/static"
    chmod 755 "$INSTALL_DIR/static/files"
    chmod 755 "$INSTALL_DIR/templates"

    # Set file permissions
    chmod 644 "$INSTALL_DIR/fileserver.py"
    chmod 755 "$INSTALL_DIR/filemanager"
    chmod 600 "$INSTALL_DIR/config.yaml"

    print_success "Permissions set"
}

install_service() {
    print_step "Installing systemd service..."

    # Get the directory where this script is located
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    cp "$SCRIPT_DIR/fileserver.service" /etc/systemd/system/glassfile.service

    systemctl daemon-reload
    systemctl enable glassfile.service

    print_success "Service installed and enabled"
}

start_service() {
    print_step "Starting service..."

    systemctl start glassfile.service
    sleep 2

    if systemctl is-active --quiet glassfile.service; then
        print_success "Service started successfully"
    else
        print_error "Service failed to start"
        echo "Check logs with: journalctl -u glassfile.service"
        return 1
    fi
}

print_summary() {
    echo ""
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}  Installation Complete!${NC}"
    echo -e "${GREEN}========================================${NC}"
    echo ""
    echo "  Installation directory: $INSTALL_DIR"
    echo "  Log directory:          $LOG_DIR"
    echo "  Service name:           glassfile.service"
    echo ""
    echo "  Web interface:          http://localhost:8080"
    echo "  Health check:           http://localhost:8080/health"
    echo ""
    echo -e "  ${CYAN}Service commands:${NC}"
    echo "    sudo systemctl start glassfile"
    echo "    sudo systemctl stop glassfile"
    echo "    sudo systemctl restart glassfile"
    echo "    sudo systemctl status glassfile"
    echo ""
    echo -e "  ${CYAN}View logs:${NC}"
    echo "    sudo journalctl -u glassfile -f"
    echo "    sudo tail -f $LOG_DIR/error.log"
    echo ""
    echo -e "  ${CYAN}CLI tool:${NC}"
    echo "    $INSTALL_DIR/filemanager config --key YOUR_API_KEY"
    echo "    $INSTALL_DIR/filemanager list"
    echo ""
    echo -e "  ${YELLOW}Next steps:${NC}"
    echo "    1. Change the default admin password"
    echo "    2. Configure Nginx reverse proxy (see nginx.conf.example)"
    echo "    3. Set up SSL/HTTPS with Let's Encrypt"
    echo "    4. Configure firewall (ufw allow 80,443/tcp)"
    echo ""
}

# Main installation flow
main() {
    print_header

    check_root
    check_python

    echo ""
    read -p "Install Glassmorphic File Manager to $INSTALL_DIR? [y/N] " -n 1 -r
    echo ""

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 0
    fi

    echo ""

    create_user
    create_directories
    copy_files
    setup_venv
    generate_credentials
    create_config
    set_permissions
    install_service
    start_service

    print_summary
}

# Run main function
main "$@"
